website: https://wiki.freedesktop.org/www/Software/fontconfig/
description: Fontconfig is a library for configuring and customizing font access.

version:
  - 2.13.91

archive: https://www.freedesktop.org/software/fontconfig/release/fontconfig-{{version}}.tar.xz

depend:
  - zlib
  - freetype
  - json-c
  - gperf # tool


compile:
  type: configure
