name: pkg-config
website:
description:

version:
  - 0.29.2

archive: https://pkg-config.freedesktop.org/releases/pkg-config-{{version}}.tar.gz
git: https://pkg-config.freedesktop.org.git

depend:

build:
  type: configure
  build_path: _build
  step:
    - "{{repo_path}}/configure --prefix={{install_path}} --with-internal-glib"
    - "make -j {{thread_num}}"
    - "make install"
