default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.0.1'
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: '\s*.patch'
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 'v2.20.0'
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.4.1'
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.31.0'
    hooks:
      - id: yapf
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v2.29.0'
    hooks:
      - id: pyupgrade
  - repo: https://github.com/yoheimuta/protolint
    rev: 'v0.35.2'
    hooks:
      - id: protolint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: 'v0.29.0'
    hooks:
      - id: markdownlint
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: 'v0.8.0.1'
    hooks:
      - id: shellcheck
  - repo: https://github.com/cpplint/cpplint
    rev: '1.5.5'
    hooks:
      - id: cpplint
        args: ['--linelength=100']
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: 'v0.6.13'
    hooks:
      - id: cmake-format
      - id: cmake-lint
  - repo: https://github.com/PyCQA/pylint
    rev: 'v2.11.1'
    hooks:
      - id: pylint
  - repo: https://github.com/PyCQA/isort
    rev: '5.10.1'
    hooks:
      - id: isort
  - repo: https://github.com/golangci/golangci-lint
    rev: 'v1.43.0'
    hooks:
      - id: golangci-lint
  - repo: https://github.com/whtsky/pre-commit-beancount-format
    rev: '2.3.4'
    hooks:
      - id: beancount-format
        files: \.bean$
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v13.0.1'
    hooks:
      - id: clang-format
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: '2.1.6'
    hooks:
      - id: shfmt
        args: ['-i', '2', '-s', '-l', '-ci']
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.4
    hooks:
      - id: cppcheck
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: '5.0.1'
    hooks:
      - id: buildifier
      # - id: buildifier-lint
  - repo: https://github.com/curoky/licenseheaders
    rev: 'v0.9.0'
    hooks:
      - id: licenseheaders
        args:
          - '--tmpl=apache-2'
          - '--owner=curoky(cccuroky@gmail.com)'
          - '--years=2021'
          - '--exclude'
          - 'README.md'
          - '*.md'
          - '*.yaml'
          - '*.yml'
          - '--files'
