name: automake
website:
description:

version:
  - 1.16.1

download:
  archive-url: http://ftp.gnu.org/gnu/automake/automake-{{version}}.tar.gz
  git-url:

depend:
  lib:
  tool:
    - autoconf

build:
  type: configure
  build_path: _build
  step:
    - '{{repo_path}}/configure --prefix={{install_path}}'
    - 'make -j {{thread_num}}'
    - 'make install'
