name: automake
website:
description:

version:
  - 1.16.1

archive: http://ftp.gnu.org/gnu/automake/automake-{{version}}.tar.gz
git:

depend:
  - autoconf

build:
  type: configure
  build_path: _build
  step:
    - "{{repo_path}}/configure --prefix={{install_path}}"
    - "make -j {{thread_num}}"
    - "make install"
