name: autoconf
website:
description:

version:
  - 2.69

download:
  archive-url: http://ftp.gnu.org/gnu/autoconf/autoconf-{{version}}.tar.gz
  git-url:

depend:
  lib:
  tool:

build:
  type: configure
  build_path: _build
  step:
    - '{{repo_path}}/configure --prefix={{install_path}}'
    - 'make -j {{thread_num}}'
    - 'make install'
