name: boost
website: https://www.boost.org/
description:

version:
  - "1.68.0"
  - "1.69.0"
  - "1.70.0"

archive: https://dl.bintray.com/boostorg/release/{{version}}/source/boost_{{version|replace('.','_')}}.tar.gz
git:

depend:

build:
  type: custom
  build_path: .
  step:
    - "./bootstrap.sh --prefix={{install_path}}"
    - "./b2 install --prefix={{install_path}} -j{{thread_num}}"
