name: bzip2
website: http://www.bzip.org/
description:

version:
  - 1.0.6

archive: https://nchc.dl.sourceforge.net/project/bzip2/bzip2-{{version}}.tar.gz
git:

depend:

build:
  type: custom
  build_path: .
  step:
    - "make"
    - "make install PREFIX={{install_path}}"
