name: c_ares
website: https://c-ares.haxx.se/
description:

version:
  - cares-1_15_0

download:
  archive-url:
  git-url: git@github.com:c-ares/c-ares.git

depend:
  lib:
  tool:

build:
  type: cmake
  build_path: _build
  step:
    - 'cmake -B {{repo_path}}/_build -S {{repo_path}}/. -DCMAKE_PREFIX_PATH="{{cmake_prefix}}" -DCMAKE_INSTALL_PREFIX={{install_path}}'
    - 'make -j {{thread_num}}'
    - 'make install'
