name: cairo
website: https://cairographics.org
description: Cairo is a 2D graphics library with support for multiple output devices.

version:
  - 1.16.0

download:
  archive-url: https://cairographics.org/releases/cairo-{{version}}.tar.xz
  git-url:

depend:
  lib:
    - zlib
    - fontconfig
    - libpng
    - pixman
  tool:

build:
  type: configure
  build_path: _build
  step:
    - '{{repo_path}}/configure --prefix={{install_path}}' # --enable-egl
    - 'make -j {{thread_num}}'
    - 'make install'
