name: cmake
website: https://cmake.org/
description:

version:
  - 3.15.0-rc3

download:
  archive-url: https://github.com/Kitware/CMake/releases/download/v{{version}}/cmake-{{version}}.tar.gz
  git-url: git@github.com:Kitware/CMake.git

depend:
  lib:
  tool:

build:
  type: configure
  build_path: _build
  step:
    - '{{repo_path}}/configure --prefix={{install_path}}'
    - 'make -j {{thread_num}}'
    - 'make install'
