name: curl
website: https://curl.haxx.se/
description:

version:
  - "7.64.0"

download:
  archive-url: http://curl.haxx.se/download/curl-{{version}}.tar.gz
  git-url:

depend:
  lib:
  tool:

build:
  type: configure
  build_path: _build
  step:
    - '{{repo_path}}/configure --prefix={{install_path}}'
    - 'make -j {{thread_num}}'
    - 'make install'
