# this a template for a repo, you can use {{version}} in download url
# and
# {{thread_num}}/{{install_path}}/{{repo_path}}/{{cmake_prefix}}
# in build command.
# all this template will be xxx by jinja.

name: demo
website:
description:

version:
  - 1.0.0

archive: https://demo.com
git: git@github.com:xxx/xxx.git

depend:
  - dep1
  - dep2

build:
  type: cmake
  build_path: _build
  step:
    - "cmake"
    - "make"
    - "make install"
