name: double-conversion
website:
description:

version:
  - 3.1.5

download:
  archive-url: https://github.com/google/double-conversion/archive/v{{version}}.tar.gz
  git-url: git@github.com:google/double-conversion.git

depend:
  lib:
  tool:

build:
  type: cmake
  build_path: _build
  step:
    - 'cmake -B {{repo_path}}/_build -S {{repo_path}}/. -DCMAKE_PREFIX_PATH="{{cmake_prefix}}" -DCMAKE_INSTALL_PREFIX={{install_path}}'
    - 'make -j {{thread_num}}'
    - 'make install'
