name: fbthrift
website: https://github.com/facebook/fbthrift
description: Facebook's branch of Apache Thrift, including a new C++ server.

version:
  - 2019.07.01.00

archive: https://github.com/facebook/fbthrift/archive/v{{version}}.tar.gz
git: git@github.com:facebook/fbthrift.git

depend:
  - zstd
  - zlib
  - bison
  - googletest
  - flex
  - mstch
  - yarpl
  - gflags
  - wangle
  - glog
  - krb5
  - fizz
  - folly
  - boost
  - openssl

build:
  type: cmake
  build_path: _build
  step:
    - 'cmake -B {{repo_path}}/_build -S {{repo_path}}/. -DCMAKE_PREFIX_PATH="{{cmake_prefix}}" -DCMAKE_INSTALL_PREFIX={{install_path}}'
    - "make -j {{thread_num}}"
    - "make install"
