name: fcitx5-gtk
website:
description: gtk im module and glib based dbus client library

version:
  - master

archive:
# git: git@gitlab.com:fcitx/fcitx5-gtk.git
git: https://gitlab.com/fcitx/fcitx5-gtk.git

depend:
  - fcitx5

build:
  type: cmake
  build_path: _build
  step:
    - 'cmake -B {{repo_path}}/_build -S {{repo_path}}/. -DCMAKE_PREFIX_PATH="{{cmake_prefix}}" -DCMAKE_INSTALL_PREFIX={{install_path}} -DENABLE_GTK2_IM_MODULE=OFF'
    - "make -j {{thread_num}}"
    - "make install"
