name: file-next
website:
description:

version:
  - 1.16

archive:
git: git@github.com:petdance/file-next.git

depend:

build:
  type: custom
  build_path: .
  step:
    - perl Makefile.PL INSTALL_BASE={{install_path}}
    - make
    - make test
    - make install
