name: fizz
website: https://github.com/facebookincubator/fizz
description: C++14 implementation of the TLS-1.3 standard

version:
  - 2019.07.08.00

archive: https://github.com/facebookincubator/fizz/archive/v{{version}}.tar.gz
git: git@github.com:facebookincubator/fizz.git

depend:
  - zlib
  - double-conversion
  - libevent
  - gflags
  - openssl
  - folly
  - libsodium

build:
  type: cmake fizz
  build_path: _build
  step:
    - 'cmake -B {{repo_path}}/_build -S {{repo_path}}/fizz -DCMAKE_PREFIX_PATH="{{cmake_prefix}}" -DCMAKE_INSTALL_PREFIX={{install_path}} -DBUILD_TESTS=OFF'
    - "make -j {{thread_num}}"
    - "make install"

# Problem1: undefined reference to 'FlagRegisterer::FlagRegisterer'
# solution1: deletefizz/CMakeLists.txt#L60-L72
##find_package(gflags CONFIG QUIET)
##...
##else()
