name: fizz
website:
description:

version:
  - v2019.04.22.00

archive:
git: git@github.com:facebookincubator/fizz.git

depend:
  - zlib
  - double-conversion
  - libevent
  - gflags
  - openssl
  - folly
  - libsodium

build:
  type: cmake fizz
  build_path: _build
  step:
    - 'cmake -B {{repo_path}}/_build -S {{repo_path}}/fizz -DCMAKE_PREFIX_PATH="{{cmake_prefix}}" -DCMAKE_INSTALL_PREFIX={{install_path}} -DBUILD_TESTS=OFF'
    - "make -j {{thread_num}}"
    - "make install"
