name: fmt
website: https://fmt.dev
description: fmt is an open-source formatting library for C++. It can be used as a safe and fast alternative to (s)printf and iostreams.

version:
  - "5.3.0"

archive: https://github.com/fmtlib/fmt/archive/{{version}}.tar.gz
git:

depend:

build:
  type: cmake
  build_path: _build
  step:
    - 'cmake -S {{repo_path}}/. -DCMAKE_PREFIX_PATH="{{cmake_prefix}}" -DCMAKE_INSTALL_PREFIX={{install_path}} -DFMT_TEST=OFF'
    - "make -j {{thread_num}}"
    - "make install"
