name: folly
website: https://github.com/facebook/folly
description: An open-source C++ library developed and used at Facebook.

version:
  - 2019.06.17.00

archive: https://github.com/facebook/folly/archive/v{{version}}.tar.gz
git: git@github.com:facebook/folly.git

depend:
  - zstd
  - snappy
  - lzma
  - lz4
  - double-conversion
  - libevent
  - gflags
  - glog
  - boost
  - openssl

build:
  type: cmake
  build_path: _build
  step:
    - 'cmake -B {{repo_path}}/_build -S {{repo_path}}/. -DCMAKE_PREFIX_PATH="{{cmake_prefix}}" -DCMAKE_INSTALL_PREFIX={{install_path}}'
    - "make -j {{thread_num}}"
    - "make install"
