name: glog
website: https://github.com/google/glog
description: C++ implementation of the Google logging module

version:
  - 0.4.0

archive: https://github.com/google/glog/archive/v{{version}}.tar.gz
git: git@github.com:google/glog

depend:
  - gflags

build:
  type: cmake
  build_path: _build
  step:
    - 'cmake -B {{repo_path}}/_build -S {{repo_path}}/. -DCMAKE_PREFIX_PATH="{{cmake_prefix}}" -DCMAKE_INSTALL_PREFIX={{install_path}} -DBUILD_SHARED_LIBS=OFF'
    - "make -j {{thread_num}}"
    - "make install"

# build:
#   type: cmake
#   build_path: .
#   step:
#     - "{{repo_path}}/autogen.sh"
#     - "{{repo_path}}/configure --prefix={{install_path}}"
#     - "make -j {{thread_num}}"
#     - "make install"
