name: googletest
website:
description: Googletest - Google Testing and Mocking Framework


version:
  - 1.8.1

archive: https://github.com/google/googletest/archive/release-{{version}}.tar.gz
git: git@github.com:google/googletest.git

depend:

build:
  type: cmake
  build_path: _build
  step:
    - 'cmake -B {{repo_path}}/_build -S {{repo_path}}/. -DCMAKE_PREFIX_PATH="{{cmake_prefix}}" -DCMAKE_INSTALL_PREFIX={{install_path}}'
    - "make -j {{thread_num}}"
    - "make install"
