name: gperf
website: https://www.gnu.org/software/gperf
description: Perfect hash function generator

version:
  - 3.1

download:
  archive-url: https://ftp.gnu.org/gnu/gperf/gperf-{{version}}.tar.gz
  git-url:

depend:
  lib:
  tool:

build:
  type: configure
  build_path: _build
  step:
    - '{{repo_path}}/configure --prefix={{install_path}}'
    - 'make -j {{thread_num}}'
    - 'make install'
