name: gtest
website:
description:

version:
  - release-1.8.1

archive:
git: git@github.com:google/googletest.git

depend:

build:
  type: cmake
  build_path: _build
  step:
    - 'cmake -B {{repo_path}}/_build -S {{repo_path}}/. -DCMAKE_PREFIX_PATH="{{cmake_prefix}}" -DCMAKE_INSTALL_PREFIX={{install_path}}'
    - "make -j {{thread_num}}"
    - "make install"
