name: harfbuzz
website: https://wiki.freedesktop.org/www/Software/HarfBuzz
description:

version:
  - 2.5.1

download:
  archive-url: https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-{{version}}.tar.xz
  git-url:

depend:
  lib:
  tool:

build:
  type: configure
  build_path: _build
  step:
    - '{{repo_path}}/configure --prefix={{install_path}}'
    - 'make -j {{thread_num}}'
    - 'make install'
