name: help2man
website:
description:

version:
  - 1.47.9

archive: http://ftp.gnu.org/gnu/help2man/help2man-{{version}}.tar.xz
git:

depend:

build:
  type: configure
  build_path: _build
  step:
    - "{{repo_path}}/configure --prefix={{install_path}}"
    - "make -j {{thread_num}}"
    - "make install"
