name: krb5
website:
description:

version:
  - krb5-1.16.1-final

archive:
git: git@github.com:krb5/krb5.git

depend:
  - automake
  - bison

build:
  type: custom
  build_path: .
  step:
    - "cd src"
    - "autoreconf -ivf"
    - "{{repo_path}}/src/configure --prefix={{install_path}}"
    - "make -j {{thread_num}}"
    - "make install"
