# this repo must be with root, because need chown root:root

name: libfuse
website:
description: The reference implementation of the Linux FUSE (Filesystem in Userspace) interface

version:
  - 3.5.0

archive: https://github.com/libfuse/libfuse/releases/download/fuse-{{version}}/fuse-{{version}}.tar.xz
git: git@github.com:libfuse/libfuse.git

depend:

build:
  type: ninja
  build_path: _build
  step:
    - "meson {{repo_path}} --prefix={{install_path}}"
    - "ninja -j {{thread_num}}"
    - "ninja install"
