name: libsodium
website: https://libsodium.org
description:

version:
  - 1.0.16

archive: https://github.com/jedisct1/libsodium/releases/download/{{version}}/libsodium-{{version}}.tar.gz
git: https://github.com/jedisct1/libsodium.git

depend:

build:
  type: configure
  build_path: _build
  step:
    - "{{repo_path}}/configure --prefix={{install_path}}"
    - "make -j {{thread_num}}"
    - "make install"
