name: libtiff
website: https://libtiff.gitlab.io/libtiff/
description: TIFF Library and Utilities

version:
  - 4.0.10

download:
  archive-url: http://download.osgeo.org/libtiff/tiff-{{version}}.tar.gz
  git-url:

depend:
  lib:
    - zlib
  tool:

build:
  type: cmake
  build_path: _build
  step:
    - 'cmake -B {{repo_path}}/_build -S {{repo_path}}/. -DCMAKE_PREFIX_PATH="{{cmake_prefix}}" -DCMAKE_INSTALL_PREFIX={{install_path}}'
    - 'make -j {{thread_num}}'
    - 'make install'
