# not complete!!!
name: libxml
website: http://www.xmlsoft.org
description: The XML C parser and toolkit of Gnome

version:
  - 2.9.9

download:
  archive-url: ftp://xmlsoft.org/libxml2/libxml2-{{version}}.tar.gz
  git-url:

depend:
  lib:
  tool:

build:
  type: configure
  build_path: _build
  step:
    - '{{repo_path}}/configure --prefix={{install_path}} --with-python=no'
    - 'make -j {{thread_num}}'
    - 'make install'
