name: libxkbfile
website: https://gitlab.freedesktop.org/xorg/lib/libxkbfile
description: libxkbfile is used by the X servers and utilities to parse the XKB configuration data files.

version:
  - 1.1.0

archive: https://www.x.org/archive//individual/lib/libxkbfile-{{version}}.tar.gz
git: https://gitlab.freedesktop.org/xorg/lib/libxkbfile.git

depend:

build:
  type: configure
  build_path: _build
  step:
    - "{{repo_path}}/configure --prefix={{install_path}}"
    - "make -j {{thread_num}}"
    - "make install"
