name: lz4
website: http://www.lz4.org
description: Extremely Fast Compression algorithm

version:
  - 1.9.1

archive: https://github.com/lz4/lz4/archive/v{{version}}.tar.gz
git: git@github.com:lz4/lz4.git

depend:

build:
  type: cmake contrib/cmake_unofficial
  build_path: _build
  step:
    - 'cmake -B {{repo_path}}/_build -S {{repo_path}}/contrib/cmake_unofficial -DCMAKE_PREFIX_PATH="{{cmake_prefix}}" -DCMAKE_INSTALL_PREFIX={{install_path}}'
    - "make -j {{thread_num}}"
    - "make install"
