name: mosh
website: https://mosh.org
description:

version:
  - 1.3.2

download:
  archive-url: https://github.com/mobile-shell/mosh/releases/download/mosh-{{version}}/mosh-{{version}}.tar.gz
  git-url: https://github.com/mobile-shell/mosh.git

depend:
  lib:
    - ncurses
    - zlib
    - protobuf
    - openssl
  tool:

build:
  type: configure
  build_path: _build
  step:
    - '{{repo_path}}/configure --prefix={{install_path}} CPPFLAGS=-std=c++11'
    - 'make -j {{thread_num}}'
    - 'make install'
