name: mpc
website:
description:

version:
  - 1.1.0

download:
  archive-url: http://ftp.gnu.org/gnu/mpc/mpc-{{version}}.tar.gz
  git-url:

depend:
  lib:
    - gmp
    - mpfr
  tool:

build:
  type: configure
  build_path: _build
  step:
    - '{{repo_path}}/configure --prefix={{install_path}}'
    - 'make -j {{thread_num}}'
    - 'make install'
