name: mstch
website: https://github.com/no1msd/mstch
description: mstch is a complete implementation of {{mustache}} templates using modern C++

version:
  - 1.0.2

archive: https://github.com/no1msd/mstch/archive/{{version}}.tar.gz
git: git@github.com:no1msd/mstch.git

depend:
  - boost

build:
  type: cmake
  build_path: _build
  step:
    - 'cmake -B {{repo_path}}/_build -S {{repo_path}}/. -DCMAKE_PREFIX_PATH="{{cmake_prefix}}" -DCMAKE_INSTALL_PREFIX={{install_path}}'
    - "make -j {{thread_num}}"
    - "make install"
