name: mstch
website:
description:

version:
  - 1.0.2

archive:
git: git@github.com:no1msd/mstch.git

depend:
  - boost

build:
  type: cmake
  build_path: _build
  step:
    - 'cmake -B {{repo_path}}/_build -S {{repo_path}}/. -DCMAKE_PREFIX_PATH="{{cmake_prefix}}" -DCMAKE_INSTALL_PREFIX={{install_path}}'
    - "make -j {{thread_num}}"
    - "make install"
