name: ninja
website: https://ninja-build.org/
description: Ninja is a small build system with a focus on speed.

version:
  - v1.9.0

download:
  # archive-url: https://github.com/ninja-build/ninja/releases/download/{{version}}/ninja-linux.zip binary file
  archive-url: https://github.com/ninja-build/ninja/archive/v1.9.0.tar.gz
  git-url:

depend:
  lib:
  tool:

build:
  type: configure
  build_path: _build
  step:
    - '{{repo_path}}/configure.py --bootstrap'
    - 'cp {{repo_path}}ninja {{install_path}}/bin/'
