name: openssl
website: https://www.openssl.org
description:

version:
  - 1.1.1b

download:
  archive-url: https://www.openssl.org/source/openssl-{{version}}.tar.gz
  git-url:

depend:
  lib:
  tool:

build:
  type: custom
  build_path: .
  step:
    - '{{repo_path}}/config --prefix={{install_path}} --openssldir={{install_path}}/ssl'
    - 'make -j {{thread_num}}'
    - 'make install'
