name: polipo
website: https://www.irif.fr/~jch/software/polipo/
description:

version:
  - 1.1.1

download:
  archive-url: https://github.com/jech/polipo/archive/polipo-{{version}}.tar.gz
  git-url:

depend:
  lib:
  tool:

build:
  type: custom
  build_path: .
  step:
    - 'make'
    - 'cp {{repo_path}}/polipo {{install_path}}/bin'
