name: python
website:
description:

version:
  - 3.6.3

download:
  archive-url: https://www.python.org/ftp/python/{{version}}/Python-{{version}}.tgz
  git-url:

depend:
  lib:
  tool:

build:
  type: configure
  build_path: _build
  step:
    - '{{repo_path}}/configure --prefix={{install_path}} --enable-optimizations'
    - 'make -j {{thread_num}}'
    - 'make install'
