name: python
website:
description:

version:
  - 3.7.3

download:
  archive-url: https://www.python.org/ftp/python/{{version}}/Python-{{version}}.tgz
  git-url:

depend:
  lib:
    - lzma # option deps
  tool:

build:
  type: configure
  build_path: _build
  step:
    # --enable-optimizations will run test, very slow
    # - '{{repo_path}}/configure --prefix={{install_path}} --enable-optimizations'
    - '{{repo_path}}/configure --prefix={{install_path}}'
    - 'make -j {{thread_num}}'
    - 'make install'
