name: rapidjson
website: http://rapidjson.org/
description:

version:
  - master

archive:
git: git@github.com:Tencent/rapidjson.git

depend:

build:
  type: cmake
  build_path: _build
  step:
    - 'cmake -B {{repo_path}}/_build -S {{repo_path}}/. -DCMAKE_PREFIX_PATH="{{cmake_prefix}}" -DCMAKE_INSTALL_PREFIX={{install_path}} -DRAPIDJSON_BUILD_DOC=OFF -DRAPIDJSON_BUILD_EXAMPLES=OFF -DRAPIDJSON_BUILD_TESTS=OFF'
    - "make -j {{thread_num}}"
    - "make install"
