name: sshfs
website:
description: A network filesystem client to connect to SSH servers

version:
  - 3.5.2

download:
  archive-url: https://github.com/libfuse/sshfs/releases/download/sshfs-{{version}}/sshfs-{{version}}.tar.xz
  git-url: git@github.com:libfuse/sshfs.git

depend:
  lib:
    - libfuse
    - glib
  tool:

build:
  type: ninja
  build_path: _build
  step:
    - 'meson {{repo_path}} --prefix={{install_path}}'
    - 'ninja -j {{thread_num}}'
    - 'ninja install'
