name: tree
website:
description:

version:
  - 1.8.0

download:
  archive-url: http://mama.indstate.edu/users/ice/tree/src/tree-{{version}}.tgz
  git-url:

depend:
  lib:
  tool:

build:
  type: custom
  build_path: .
  step:
    - 'make'
    - 'cp {{repo_path}}/tree {{install_path}}/bin'
