# this repo must be with root, because need chgrp
# chgrp: changing group of '.../bin/wall': Operation not permitted

name: util-linux
website: https://en.wikipedia.org/wiki/Util-linux
description: util-linux is a random collection of Linux utilities


version:
  - 2.34

download:
  archive-url: https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v{{version}}/util-linux-{{version}}-rc2.tar.xz
  git-url: git@github.com:karelzak/util-linux.git

depend:
  lib:
  tool:

build:
  type: configure
  build_path: .
  step:
    - '{{repo_path}}/configure --prefix={{install_path}}'
    - 'make -j {{thread_num}}'
    - 'make install'
