name: vim
website: https://www.vim.org/
description:

version:
  # - 8.1.1640
  - 8.1.0996

download:
  archive-url: https://github.com/vim/vim/archive/v{{version}}.tar.gz
  git-url: git@github.com:vim/vim.git

depend:
  lib:
    - ncurses
    - libiconv # vim error: cannot compute sizeof (off_t) , need export to LD_LIBRARY_PATH
  tool:

build:
  type: configure
  build_path: .
  step:
    - '{{repo_path}}/configure --prefix={{install_path}} --with-tlib="ncurses" '
    - 'make -j {{thread_num}}'
    - 'make install'
