name: xcb-util-vm
website: https://xcb.freedesktop.org/
description: The X protocol C-language Binding (XCB) is a replacement for Xlib featuring a small footprint, latency hiding, direct access to the protocol, improved threading support, and extensibility.

version:
  - 0.4.1

download:
  archive-url: https://xcb.freedesktop.org/dist/xcb-util-wm-{{version}}.tar.gz
  git-url:

depend:
  lib:
  tool:

build:
  type: configure
  build_path: _build
  step:
    - '{{repo_path}}/configure --prefix={{install_path}}'
    - 'make -j {{thread_num}}'
    - 'make install'
