name: yarpl
website: http://rsocket.io/
description:

version:
  - master

archive: https://github.com/rsocket/rsocket-cpp/archive/{{version}}.zip
git: git@github.com:rsocket/rsocket-cpp.git

depend:
  - googletest
  - double-conversion
  - gflags
  - glog
  - folly
  - boost

build:
  type: cmake
  build_path: _build
  step:
    - 'cmake -B {{repo_path}}/_build -S {{repo_path}}/. -DCMAKE_PREFIX_PATH="{{cmake_prefix}}" -DCMAKE_INSTALL_PREFIX={{install_path}} -DBUILD_TESTS=OFF -DBUILD_EXAMPLES= -DBUILD_BENCHMARKS=OFF'
    - "make -j {{thread_num}}"
    - "make install"
