name: yarpl
website: http://rsocket.io/
description:

version:
  - master

download:
  archive-url:
  git-url: git@github.com:rsocket/rsocket-cpp.git

depend:
  lib:
    - gtest
    - double-conversion
    - gflags
    - glog
    - folly
    - boost
  tool:

build:
  type: cmake
  build_path: _build
  step:
    - 'cmake -B {{repo_path}}/_build -S {{repo_path}}/. -DCMAKE_PREFIX_PATH="{{cmake_prefix}}" -DCMAKE_INSTALL_PREFIX={{install_path}} -DBUILD_TESTS=OFF -DBUILD_EXAMPLES= -DBUILD_BENCHMARKS=OFF'
    - 'make -j {{thread_num}}'
    - 'make install'
