name: zsh
website: http://www.zsh.org
description:

version:
  - 5.7.1

download:
  archive-url: https://jaist.dl.sourceforge.net/project/zsh/zsh/{{version}}/zsh-{{version}}.tar.xz
  git-url:

depend:
  lib:
    - ncurses
  tool:

build:
  type: configure
  build_path: .
  step:
    - '{{repo_path}}/configure --prefix={{install_path}} --with-term-lib="ncurses"'
    - 'make -j {{thread_num}}'
    - 'make install'
