name: zstd
website: http://www.zstd.net
description: Zstandard - Fast real-time compression algorithm

version:
  - 1.4.0

archive: https://github.com/facebook/zstd/releases/download/v{{version}}/zstd-{{version}}.tar.gz
git: git@github.com:facebook/zstd.git

depend:

build:
  type: cmake build/cmake
  build_path: _build
  step:
    - 'cmake -B {{repo_path}}/_build -S {{repo_path}}/build/cmake -DCMAKE_PREFIX_PATH="{{cmake_prefix}}" -DCMAKE_INSTALL_PREFIX={{install_path}}'
    - "make -j {{thread_num}}"
    - "make install"
