website:
description:

version:
  - 0.29.2

git: https://pkg-config.freedesktop.org.git
archive: https://pkg-config.freedesktop.org/releases/pkg-config-{{version}}.tar.gz

compile:
  type: configure
  args: --with-internal-glib
