name: Pre Commit

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: curoky/formatter:latest
    steps:
      - uses: actions/checkout@v2
      - uses: pre-commit/action@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
